
export default new Map([
["src/content/recortes/blogging-is.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Frecortes%2Fblogging-is.mdx&astroContentModuleFlag=true")],
["src/content/morsels/morsel-16.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmorsels%2Fmorsel-16.mdx&astroContentModuleFlag=true")],
["src/content/morsels/morsel-20.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmorsels%2Fmorsel-20.mdx&astroContentModuleFlag=true")],
["src/content/morsels/morsel-23.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmorsels%2Fmorsel-23.mdx&astroContentModuleFlag=true")],
["src/content/recortes/the-near-infinity-of-pixels.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Frecortes%2Fthe-near-infinity-of-pixels.mdx&astroContentModuleFlag=true")],
["src/content/recortes/wander-in-porto.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Frecortes%2Fwander-in-porto.mdx&astroContentModuleFlag=true")],
["src/content/morsels/morsel-28.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fmorsels%2Fmorsel-28.mdx&astroContentModuleFlag=true")],
["src/content/posts/apis-vs-chatbots.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fapis-vs-chatbots.mdx&astroContentModuleFlag=true")],
["src/content/recortes/websites-like-service-stations.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Frecortes%2Fwebsites-like-service-stations.mdx&astroContentModuleFlag=true")],
["src/content/recortes/where-theres-gold.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Frecortes%2Fwhere-theres-gold.mdx&astroContentModuleFlag=true")],
["src/content/posts/generative-ai-bored-privilege.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fgenerative-ai-bored-privilege.mdx&astroContentModuleFlag=true")],
["src/content/posts/github-as-a-cms.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fgithub-as-a-cms.mdx&astroContentModuleFlag=true")],
["src/content/posts/good-faith-ai-you-first.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fgood-faith-ai-you-first.mdx&astroContentModuleFlag=true")],
["src/content/posts/media-of-the-year-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fmedia-of-the-year-2025.mdx&astroContentModuleFlag=true")],
["src/content/posts/my-week-in-lisbon.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fmy-week-in-lisbon.mdx&astroContentModuleFlag=true")],
["src/content/posts/refactored-my-website.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Frefactored-my-website.mdx&astroContentModuleFlag=true")],
["src/content/posts/short-form-blogs-subversive.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fshort-form-blogs-subversive.mdx&astroContentModuleFlag=true")],
["src/content/posts/slow-connection-speeds-everybody-problem.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fslow-connection-speeds-everybody-problem.mdx&astroContentModuleFlag=true")],
["src/content/posts/some-brief-thoughts-on web-dev-and-web-performance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fsome-brief-thoughts-on+web-dev-and-web-performance.mdx&astroContentModuleFlag=true")],
["src/content/posts/vicuna-made-me-laugh.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fposts%2Fvicuna-made-me-laugh.mdx&astroContentModuleFlag=true")]]);
		