---
title: 'A response to “Accidental anonymity”'
description: "Maybe I'm braver than I thought"
published: true
pubDate: '24 Jun 2026'
tags:
  - life
  - music
  - blogging
---

[Jacky Alciné](https://www.jacky.wtf/) [posted an article by Tom MacWright on Bluesky](https://bsky.app/profile/omg.jacky.wtf/post/3mp22w34ljc2m) entitled [“Accidental anonymity”](https://macwright.com/2026/06/24/accidental-anonymity). He talks about the emails and applications he's received and reviewed that appear to be AI-generated from start to finish and why it's a sad state of affairs (and I agree). Here's an except:

> [...] I've written and sung songs, and published my artwork and writing on the internet for fifteen years, and a lot of the reaction I get is about how other people couldn't because they don't know how or don't think theirs is good enough or whatever, but let me be blunt for a brief moment: putting your art, writing, expression out to be judged by others is an act of bravery as much as talent, and a lot of people lack bravery. Sorry to say it but if you need your work to be polished and beyond reproach, that's a determination and character problem, not a skill problem.

I've been doing the same for about as long as Tom by the sounds of it (18 years of blogging, 16 years of music production) and once I started making stuff under the assumption that nobody would engage with it but I liked what I made anyway, it was so freeing.

It's not that i don't *want* anyone to engage with it or that I truly think absolutely nobody would ever read or listen because they have but relieving myself of the expectation and not going after it meant I could concentrate on what **I** wanted from what **I** made. The second I defer all of that to someone—or some_thing_ else, it's not mine. I can't, in good conscience, say I made a thing when it was completed generated by Not Me.

And it's still a big risk because I fear rejection and criticism like anyone else who fears rejection and criticism. But I have to be honest to myself and what I make. I want to share it with others and sure maybe that's to feel validated but that's a personal decision. I'm not pretending to be more than I am and I still worry that one day someone will respond to something I've published with the kind of criticism that'll send my head spinning but that's a bridge I'll cross if I come to it. Until then, expect work of objectively varied quality and within the realms of reproach.